name: laravel_docs_alfred_workflow
description: Search the Laravel documentation using Alfred

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.11

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  alfred_workflow: ^0.3.0+1
  algolia: ^1.1.2
  args: ^2.4.0
  cli_script: ^0.3.0
  envied: ^0.3.0
  html_unescape: ^2.0.0
  collection: ^1.17.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  envied_generator: ^0.3.0
  json_serializable: ^6.6.1
  lints: ^2.0.1
